server:
  port: 10508

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      url: jdbc:mysql://39.106.116.74:3306/Purchase?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: wyxnb
      driver-class-name: com.mysql.cj.jdbc.Driver
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
    timeout: 0
    jedis:
      pool:
        max-active: 100
        max-wait:
        max-idle: 10
logging:
  path:
  file:
